import { NoteType } from "@/types/NoteType";

export const notes: NoteType[] = [
  // 📌 Pinned notes (5)
  {
    id: 1,
    title: "Learn React Native",
    isPinned: true,
    description: 'Hello',
    createdAt: new Date(),
  },
  {
    id: 2,
    title: "Notes App Features",
    description: "Pinned notes, search, swipe delete, dark mode.",
    isPinned: true,
    createdAt: new Date(),
  },
  {
    id: 3,
    title: "Daily Goals",
    description: "Code 2 hours, read docs, practice UI.",
    isPinned: true,
    createdAt: new Date(),
  },
  {
    id: 4,
    title: "Important Ideas",
    description: "Build apps that solve real problems.",
    isPinned: true,
    createdAt: new Date(),
  },
  {
    id: 5,
    title: "React Native Tips",
    description: "Use FlatList, avoid ScrollView for large lists.",
    isPinned: true,
    createdAt: new Date(),
  },

  // 📝 Normal notes (15)
  {
    id: 6,
    title: "Buy groceries",
    description: "Milk, eggs, bread, noodles.",
    isPinned: false,
    createdAt: new Date(),
  },
  {
    id: 7,
    title: "Workout",
    description: "Pushups, squats, plank.",
    isPinned: false,
    createdAt: new Date(),
  },
  {
    id: 8,
    title: "Watch tutorial",
    description: "FlatList optimization in React Native.",
    isPinned: false,
    createdAt: new Date(),
  },
  {
    id: 9,
    title: "UI ideas",
    description: "Minimal design with soft shadows.",
    isPinned: false,
    createdAt: new Date(),
  },
  {
    id: 10,
    title: "Fix bugs",
    description: "Search not updating list correctly.",
    isPinned: false,
    createdAt: new Date(),
  },
  {
    id: 11,
    title: "Read docs",
    description: "Expo Router navigation patterns.",
    isPinned: false,
    createdAt: new Date(),
  },
  {
    id: 12,
    title: "App name ideas",
    description: "QuickNote, TinyNotes, MemoX.",
    isPinned: false,
    createdAt: new Date(),
  },
  {
    id: 13,
    title: "Clean code",
    description: "Refactor components and hooks.",
    isPinned: false,
    createdAt: new Date(),
  },
  {
    id: 14,
    title: "Keyboard issue",
    description: "Dismiss keyboard on background tap.",
    isPinned: false,
    createdAt: new Date(),
  },
  {
    id: 15,
    title: "Icons",
    description: "Use Entypo or Lucide icons.",
    isPinned: false,
    createdAt: new Date(),
  },
  {
    id: 16,
    title: "Animations",
    description: "Use LayoutAnimation or Reanimated.",
    isPinned: false,
    createdAt: new Date(),
  },
  {
    id: 17,
    title: "Testing",
    description: "Test FlatList rendering performance.",
    isPinned: false,
    createdAt: new Date(),
  },
  {
    id: 18,
    title: "Dark mode",
    description: "Implement theme toggle.",
    isPinned: false,
    createdAt: new Date(),
  },
  {
    id: 19,
    title: "Backup",
    description: "Save notes using AsyncStorage.",
    isPinned: false,
    createdAt: new Date(),
  },
  {
    id: 20,
    title: "Publish app",
    description: "Prepare APK and Play Store listing.",
    isPinned: false,
    createdAt: new Date(),
  },
];